---
- name: Install Debian packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - libevent-dev
    - libncurses-dev
    - pkg-config
    - wget
    - curl
    - make
    - gcc
