---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Checking installed version of tmux
  shell: /usr/bin/test "$({{tmux_path}}bin/tmux -V 2> /dev/null)" = {{ tmux_version }}
  register: wanted_version_installed
  ignore_errors: True
  changed_when: "wanted_version_installed.rc == 1"

- name: Download tmux {{tmux_version}}
  get_url: url={{tmux_tarball_url}} dest={{tmux_tmp_dir}}{{tmux_file_name}} timeout=120
  when: wanted_version_installed.rc == 1

- name: Unpack tmux {{tmux_version}}
  command: tar -xzf {{tmux_file_name}} chdir={{tmux_tmp_dir}}
  when: wanted_version_installed.rc == 1

- name: Compile and install tmux {{tmux_version}}
  shell: |
   ./configure --prefix={{tmux_path}} &&
            make &&
            make install
            chdir={{tmux_tmp_dir}}{{tmux_file_tag}}
  sudo: true
  when: wanted_version_installed.rc == 1

- name: Register remote PATH File
  shell: "echo $PATH"
  register: tmux_path_out

